# Generated by Django 5.1.4 on 2025-01-19 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_completion_rate', models.FloatField(default=0)),
                ('monthly_completion_rate', models.FloatField(default=0)),
                ('best_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_habit_analytics', to='habit_models.habit')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit_models.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit_models.user')),
                ('worst_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worst_habit_analytics', to='habit_models.habit')),
            ],
        ),
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_habits', models.ManyToManyField(to='habit_models.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit_models.user')),
            ],
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_count', models.IntegerField(default=0)),
                ('last_completed', models.DateField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit_models.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit_models.user')),
            ],
        ),
    ]
